spring:
  application:
    name: demo
  profiles:
    active: local

---
server:
  port: 80
spring:
  profiles: local
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://123.206.62.172:3300/sell?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: Drb.199519.cq
  jpa:
    show-sql: true



#  redis:
#    host: 123.206.62.172
#    port: 6799
#    password: Drb.199519.cq





